name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build app
        run: ./scripts/buildprod.sh


      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      # Option 1
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker build -t us-east1-docker.pkg.dev/notely-448014/notely-ar-repo/notely:latest .
          docker push us-east1-docker.pkg.dev/notely-448014/notely-ar-repo/notely:latest

      # Option 2
      # Need to add the cloudbuild.yaml as well, ref https://cloud.google.com/build/docs/securing-builds/store-manage-build-logs#yaml
      # Must not use default service account
      # TODO - add cloudbuild.yaml file
      # - name: Build and push Docker image
      #   run: gcloud builds submit --tag us-east1-docker.pkg.dev/notely-448014/notely-ar-repo/notely:latest . --service-account=cloud-run-deployer@notely-448014.iam.gserviceaccount.com
        
